services:
  db:
    container_name: postgresSQL-17
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: aboutmeDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: