services:
  db:
    container_name: postgresSQL-17
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: aboutmeDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4-8.13
    image: dpage/pgadmin4:8.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin: