services:
  pgadmin:
    container_name: pgadmin4-8.13
    image: dpage/pgadmin4:8.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root # don't use this password for dev server ;p
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgadmin: